name: publish

concurrency: production

on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: Bump level
        options:
          - major
          - minor
          - patch
      execute:
        type: boolean
        description: Actually publish (not dry run)

jobs:
  release-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      sign: ${{ inputs.execute == true }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SIGNING_ENDPOINT: ${{ secrets.AZURE_SIGNING_ENDPOINT }}
      AZURE_SIGNING_ACCOUNT: ${{ secrets.AZURE_SIGNING_ACCOUNT }}
      AZURE_SIGNING_PROFILE: ${{ secrets.AZURE_SIGNING_PROFILE }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  publish:
    runs-on: windows-latest
    environment: publish
    needs: release-deploy
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cd
        run: |
          git config user.name 'YOUR.GG Overlay Continuous Deployment'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://npm.pkg.github.com'
          scope: '@your-gg'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Bump node package version
        id: bump
        run: |
          npm config set git-tag-version=false
          $ver = pnpm --filter "@your-gg/*" exec npm version ${{ github.event.inputs.level }}
          $ver=$ver[0]
          git commit -a -m "chore: Bump node package version"
          "version=" + $ver.substring(1) >> $env:GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ inputs.execute && needs.release-deploy.outputs.signed-artifact-id || needs.release-deploy.outputs.unsigned-artifact-id }}
          path: 'packages/core'
          merge-multiple: true

      - name: Publish node package
        run: pnpm ci:publish ${{ !inputs.execute && '--dry-run' || '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: ${{ inputs.execute }}
        uses: softprops/action-gh-release@v2
        with:
          name: 'YOUR.GG Overlay v${{ steps.bump.outputs.version }}'
          draft: false
          generate_release_notes: true
          make_latest: true
          tag_name: "v${{ steps.bump.outputs.version }}"
          target_commitish: '${{ github.ref }}'
          files: |
            packages/core/yourgg_overlay-aarch64.dll
            packages/core/yourgg_overlay-x86.dll
            packages/core/yourgg_overlay-x64.dll
            packages/core/yourgg-injector-x64.exe
